spack:
  concretizer:
    unify: when_possible

  view: false
  include: []

  definitions:
  - compilers: ['%aocc', '%apple-clang', '%cce', '%clang', '%gcc', '%intel', 'nvhpc', '%oneapi']
  - packages:
      # Update to esmf@8.7.0b11 snapshot=b11 once available in spack
      - neptune-benchmark-env ^esmf@8.7.0b04 snapshot=b04

  specs:
    - matrix:
      - [$packages]
      - [$compilers]
