compilers:
- compiler:
    spec: aocc@4.0.0
    paths:
      cc: /p/app/compilers/amd/aocc/4.0.0/bin/clang
      cxx: /p/app/compilers/amd/aocc/4.0.0/bin/clang++
      f77: /p/app/compilers/amd/aocc/4.0.0/bin/flang
      fc: /p/app/compilers/amd/aocc/4.0.0/bin/flang
    flags:
      cflags: null
      cxxflags: null
      fflags: null
    operating_system: rhel8
    target: x86_64
    modules:
    - amd/aocc/4.0.0
    - amd/aocl/aocc/4.0
    environment: {}
    extra_rpaths: []
- compiler:
    spec: oneapi@2023.1.0
    paths:
      cc: /p/app/compilers/intel/intel-hpckit/2023.1.0-46346/compiler/2023.1.0/linux/bin/icx
      cxx: /p/app/compilers/intel/intel-hpckit/2023.1.0-46346/compiler/2023.1.0/linux/bin/icpx
      f77: /p/app/compilers/intel/intel-hpckit/2023.1.0-46346/compiler/2023.1.0/linux/bin/intel64/ifort
      fc: /p/app/compilers/intel/intel-hpckit/2023.1.0-46346/compiler/2023.1.0/linux/bin/intel64/ifort
    flags: {}
    operating_system: rhel8
    target: x86_64
    modules:
    - intel/compiler/2023.1.0
    environment:
      prepend_path:
        PATH: '/opt/rh/gcc-toolset-11/root/usr/bin'
        CPATH: '/opt/rh/gcc-toolset-11/root/usr/include'
        LD_LIBRARY_PATH: '/opt/scyld/slurm/lib64:/opt/scyld/slurm/lib64/slurm:/opt/rh/gcc-toolset-11/root/usr/lib64:/opt/rh/gcc-toolset-11/root/usr/lib'
        #/p/app/compilers/intel/intel-hpckit/2023.1.0-46346/compiler/2023.1.0/linux/compiler/lib/intel64_lin/
    extra_rpaths: []
