compilers:
- compiler:
    spec: intel@2021.10.0
    paths:
      cc: /work2/noaa/jcsda/dheinzel/oneapi/compiler/2023.2.1/linux/bin/intel64/icc
      cxx: /work2/noaa/jcsda/dheinzel/oneapi/compiler/2023.2.1/linux/bin/intel64/icpc
      f77: /work2/noaa/jcsda/dheinzel/oneapi/compiler/2023.2.1/linux/bin/intel64/ifort
      fc: /work2/noaa/jcsda/dheinzel/oneapi/compiler/2023.2.1/linux/bin/intel64/ifort
    flags:
      cflags: -diag-disable=10441
      cxxflags: -diag-disable=10441
      fflags: -diag-disable=10448
    operating_system: rocky9
    target: x86_64
    modules: []
    environment:
      prepend_path:
        LD_LIBRARY_PATH: '/work2/noaa/jcsda/dheinzel/oneapi/compiler/2023.2.1/linux/compiler/lib/intel64_lin'
      set:
        # https://github.com/ufs-community/ufs-weather-model/issues/2015#issuecomment-1864438186
        I_MPI_EXTRA_FILESYSTEM: 'ON'
    extra_rpaths: []
